"""Markdown export for prompt library."""

from __future__ import annotations

from collections import defaultdict
from typing import Any


def export_library_markdown(patterns: list[dict[str, Any]]) -> str:
    """Export prompt patterns as Markdown."""
    lines = ["# My Prompt Library", "", "> Generated by reprompt", ""]

    if not patterns:
        lines.append("No patterns found yet. Run `reprompt scan` to analyze your sessions.")
        return "\n".join(lines)

    # Summary table
    lines.append("## Overview")
    lines.append("")
    lines.append(f"**{len(patterns)} patterns** discovered across your AI sessions.")
    lines.append("")
    lines.append("| # | Pattern | Uses | Category |")
    lines.append("|---|---------|------|----------|")
    for i, p in enumerate(patterns, 1):
        pat = p["pattern_text"]
        pat_display = pat[:50] + "..." if len(pat) > 50 else pat
        lines.append(f"| {i} | {pat_display} | {p['frequency']} | {p['category']} |")
    lines.append("")

    # Group by category
    by_cat: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for p in patterns:
        by_cat[p["category"]].append(p)

    for cat, cat_patterns in sorted(by_cat.items()):
        lines.append(f"## {cat.title()}")
        lines.append("")
        for p in cat_patterns:
            text = p["pattern_text"]
            heading = text[:60] + "..." if len(text) > 60 else text
            lines.append(f"### {heading}")
            lines.append(f"- **Frequency:** {p['frequency']} times")
            lines.append(f"- **Avg length:** {p['avg_length']:.0f} chars")
            if p.get("examples"):
                lines.append("- **Examples:**")
                for ex in p["examples"][:3]:
                    lines.append(f"  - {ex}")
            lines.append("")

    return "\n".join(lines)
